sudo: required
services:
  - docker

script:
  - docker build -t "$DOCKER_USERNAME"/serverapp ./server
  - docker build -t "$DOCKER_USERNAME"/workerapp ./worker
  - docker build -t "$DOCKER_USERNAME"/nginx ./nginx
  - docker build -t "$DOCKER_USERNAME"/clientapp ./client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/serverapp
  - docker push "$DOCKER_USERNAME"/workerapp
  - docker push "$DOCKER_USERNAME"/nginx
  - docker push "$DOCKER_USERNAME"/clientapp

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: mult-docker
  env: MultDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-096191708657
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
