version: "3.3"
services:
  postgres:
    image: postgres
    restart: always

  redis:
    image: redis:alpine
    restart: always

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /server/node_modules
      - ./server:/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - HOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - /worker/node_modules
      - ./worker:/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /client/node_modules
      - ./client:/client
    # ports:
    #   - "4000:80"
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "4000:80"
